/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      "colors": {
          "on-primary": "#fbf8ff",
          "tertiary-dim": "#66496e",
          "on-error": "#fff7f7",
          "inverse-primary": "#8c95fb",
          "inverse-on-surface": "#9e9ca2",
          "on-tertiary-fixed-variant": "#6b4d73",
          "on-tertiary-container": "#614469",
          "surface-dim": "#dbd9e4",
          "surface-tint": "#4c55b6",
          "on-primary-fixed": "#000000",
          "surface-container-low": "#f5f2fb",
          "on-primary-fixed-variant": "#0f187f",
          "on-primary-container": "#000577",
          "secondary-fixed-dim": "#ffc7c4",
          "on-surface-variant": "#5f5e68",
          "error-container": "#f97386",
          "tertiary-fixed": "#f6d0fd",
          "surface-container-lowest": "#ffffff",
          "primary": "#4c55b6",
          "on-tertiary": "#fff7fb",
          "on-tertiary-fixed": "#4d3155",
          "primary-container": "#8c95fb",
          "on-secondary-container": "#9c2229",
          "surface-container-highest": "#e3e1ed",
          "tertiary": "#72547a",
          "surface-variant": "#e3e1ed",
          "on-background": "#32323b",
          "surface-container-high": "#e9e7f1",
          "on-secondary": "#fff7f6",
          "inverse-surface": "#0e0e12",
          "on-surface": "#32323b",
          "primary-fixed": "#8c95fb",
          "secondary-fixed": "#ffdad8",
          "surface-container": "#efecf6",
          "tertiary-container": "#f6d0fd",
          "on-secondary-fixed-variant": "#aa2c32",
          "surface": "#fbf8fe",
          "secondary": "#af3035",
          "error-dim": "#6b0221",
          "secondary-container": "#ffdad8",
          "primary-fixed-dim": "#7f88ec",
          "tertiary-fixed-dim": "#e8c3ef",
          "outline-variant": "#b2b1bc",
          "surface-bright": "#fbf8fe",
          "secondary-dim": "#9e232a",
          "outline": "#7a7a84",
          "on-error-container": "#6e0523",
          "background": "#fbf8fe",
          "primary-dim": "#4048a9",
          "on-secondary-fixed": "#810b19",
          "error": "#a8364b"
      },
      "borderRadius": {
          "DEFAULT": "1rem",
          "lg": "2rem",
          "xl": "3rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Plus Jakarta Sans"],
          "body": ["Plus Jakarta Sans"],
          "label": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: []
}
